<a href="https://colab.research.google.com/github/falsefoobar/CS381/blob/main/NumPy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.
Write a Python/NumPy code block that finds the distinct/unique common items between these two
arrays:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
Your output should contain only the distinct overlapping values. For example, if a 2 is found in both array a and array b,
your output should contain only one 2 even if array a contains more than one 2 within it.

In [19]:
a_set = set([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
a_set.update([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

print(list(a_set))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


2.
Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality
so that you do not need to explicitly key in every integer value.

In [2]:
import numpy as np

array = np.arange(1,16).reshape(3,5)
transpose_array = array.T
print(transpose_array)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


3.
The process of transforming a multidimensional array into a unidimensional array is referred to as “flattening”. Transform the 5x3 array shown above in Problem 2 into a unidimensional array such that the sequence of values contained within the array is as follows: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,

In [11]:
import numpy as np

array = np.arange(1,16).reshape(3,5)
transpose_array = array.T
print(transpose_array)
#flatten
flatten_array = transpose_array.T.flatten()
print(flatten_array)


[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


4.
Transform the 2-D array shown in Problem 2 into a 3 dimensional array such that the first column becomes the first dimension of the 3-D array, the second column becomes the second dimension of the 3-D array, and the third column becomes the third dimension of the 3-D array.

In [4]:
import numpy as np

array = np.arange(1,16).reshape(3,5)


result_array = array.reshape(3,5,1)

print(result_array)


[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]

 [[11]
  [12]
  [13]
  [14]
  [15]]]


5. Transform the 3-D array you created in Problem 4 back to the 2-dimensional format shown in Problem 2.

In [5]:
import numpy as np

array = np.arange(1,16).reshape(3,5)


result_array = array.reshape(3,5,1)


print(result_array.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


6. You are given the following two arrays:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
Write a Python/Numpy code block that removes from array a any items that are also present in array b.

In [22]:
a = set([12, 5, 7, 15, 3, 1, 8])
b = set([14, 6, 3, 11, 19, 12, 5])

print(list(a.difference(b)))

[8, 1, 15, 7]


7.1.
  What is the maximum yearly NYC consumption of water in millions of gallons per day?


1506 million gallons

7.2. How many calendar years are represented within this data set? NumPy's shape command is one way to find


In [47]:
from google.colab import drive
import pandas as pd
import numpy as np
file_path = '/content/drive/My Drive/Module6_Data.xlsx'

df = pd.read_excel(file_path)
print(len(df.Year))


39


7.3
What is the mean and the standard deviation of the per capita daily water consumption?

In [59]:
from google.colab import drive
import pandas as pd
import numpy as np
file_path = '/content/drive/My Drive/Module6_Data.xlsx'

df = pd.read_excel(file_path)
print(f"standard deviation per capita daily water consumption: {df['Per Capita(Gallons per person per day)'].std()}")
print(f"mean per capita daily water consumption: {df['Per Capita(Gallons per person per day)'].mean()}")


standard deviation per capita daily water consumption: 31.930973122258784
mean per capita daily water consumption: 160.30769230769232


7.4 What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array
of differences and save that to a variable called "pop_diff", then print that variable to the screen.



In [70]:
from google.colab import drive
import pandas as pd
import numpy as np
file_path = '/content/drive/My Drive/Module6_Data.xlsx'

df = pd.read_excel(file_path)
pop_diff = [].append(0)
count = len(df['New York City Population'])

for i in range(1, count):
  pop_diff.append(df['New York City Population'][i -1] - df['New York City Population'][i])

print(pop_diff)



[np.float64(-85025.0), np.float64(-65683.0), np.float64(44512.0), np.float64(-94042.0), np.float64(-61281.0), np.float64(-202731.5), np.float64(125650.5), np.float64(-108965.0), np.float64(-66742.0), np.float64(33371.0), np.float64(-83427.5), np.float64(16685.5), np.float64(50056.5), np.float64(-83427.5), np.float64(50056.5), np.float64(-66742.0), np.float64(-251520.5), np.float64(84816.0), np.float64(150019.0), np.float64(-60618.0), np.float64(-249848.0), np.float64(-64772.0), np.float64(-62582.0), np.float64(-296404.0), np.float64(232112.0), np.float64(-77222.0), np.float64(-339703.0), np.float64(230005.0), np.float64(24929.0), np.float64(-235070.0), np.float64(226545.0), np.float64(6826.0), np.float64(-161252.0), np.float64(193277.0), np.float64(-20782.0), np.float64(-119205.0), np.float64(-132414.0), np.float64(-30461.0)]
